export const PREDEFINED_RULES = [
  // ===============================================================
  // IMC SPECIES: ROHU (Labeo rohita)
  // ===============================================================
  {
    id: 'rohu-nursery',
    species: 'Rohu',
    scientific_name: 'Labeo rohita',
    culture_stage: 'Nursery',
    min_weight: null,
    max_weight: null,
    min_month: null,
    max_month: null,
    feeding_method: 'INITIAL_SPAWN_WEIGHT',
    feeding_mode: 'MANUAL',
    feeding_rate: null, // Manual feeding selection required
    rate_min: 400.0,
    rate_max: 800.0,
    priority: 30,
    source: 'Project Reference Assumption & CIFA Nursery Protocol',
    notes: 'Biomass: 1M spawn = 1.5 kg (project assumption). Reference: 400% (first 5 days), 800% (after first 5 days). Manual rate required.',
    notes_mr: 'बायोमास विचार: १० लाख स्पॉन = १.५ किलो (प्रकल्प गृहीतक). संदर्भ: ४००% (पहिले ५ दिवस), ८००% (५ दिवसांनंतर). मॅन्युअल दर आवश्यक.',
  },
  {
    id: 'rohu-rearing-m1',
    species: 'Rohu',
    scientific_name: 'Labeo rohita',
    culture_stage: 'Rearing',
    rearing_period: 'month_1',
    min_weight: null,
    max_weight: null,
    min_month: 0.0,
    max_month: 1.0,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'REFERENCE_ASSUMPTION',
    feeding_rate: 9.0,
    rate_min: 8.0,
    rate_max: 10.0,
    priority: 25,
    source: 'ICAR-CIFA Rearing Reference Protocol',
    notes: 'First month: 8–10% body weight/day (Reference range, working value: 9%)',
    notes_mr: 'पहिला महिना: ८–१०% बायोमास/दिवस (संदर्भ श्रेणी, कार्य दर: ९%)',
  },
  {
    id: 'rohu-rearing-m2',
    species: 'Rohu',
    scientific_name: 'Labeo rohita',
    culture_stage: 'Rearing',
    rearing_period: 'month_2',
    min_weight: null,
    max_weight: null,
    min_month: 1.01,
    max_month: 2.0,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'REFERENCE_ASSUMPTION',
    feeding_rate: 7.0,
    rate_min: 6.0,
    rate_max: 8.0,
    priority: 25,
    source: 'ICAR-CIFA Rearing Reference Protocol',
    notes: 'Second month: 6–8% body weight/day (Reference range, working value: 7%)',
    notes_mr: 'दुसरा महिना: ६–८% बायोमास/दिवस (संदर्भ श्रेणी, कार्य दर: ७%)',
  },
  {
    id: 'rohu-rearing-later',
    species: 'Rohu',
    scientific_name: 'Labeo rohita',
    culture_stage: 'Rearing',
    rearing_period: 'later',
    min_weight: null,
    max_weight: null,
    min_month: 2.01,
    max_month: 99.0,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'REFERENCE_ASSUMPTION',
    feeding_rate: 5.5,
    rate_min: 5.0,
    rate_max: 6.0,
    priority: 25,
    source: 'ICAR-CIFA Rearing Reference Protocol',
    notes: 'Later stages: 5–6% body weight/day (Reference range, working value: 5.5%)',
    notes_mr: 'पुढील टप्पे: ५–६% बायोमास/दिवस (संदर्भ श्रेणी, कार्य दर: ५.५%)',
  },
  {
    id: 'rohu-growout-initial',
    species: 'Rohu',
    scientific_name: 'Labeo rohita',
    culture_stage: 'Grow-out',
    growout_phase: 'initial',
    min_weight: null,
    max_weight: null,
    min_month: null,
    max_month: null,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'REFERENCE_ASSUMPTION',
    feeding_rate: 5.5,
    rate_min: 5.0,
    rate_max: 6.0,
    priority: 25,
    source: 'ICAR-CIFA Grow-out Reference Protocol',
    notes: 'Initial stage: 5–6% body weight/day (Reference range, working value: 5.5%)',
    notes_mr: 'सुरुवातीचा टप्पा: ५–६% बायोमास/दिवस (संदर्भ श्रेणी, कार्य दर: ५.५%)',
  },
  {
    id: 'rohu-growout-mid',
    species: 'Rohu',
    scientific_name: 'Labeo rohita',
    culture_stage: 'Grow-out',
    growout_phase: 'mid',
    min_weight: null,
    max_weight: null,
    min_month: null,
    max_month: null,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'REFERENCE_ASSUMPTION',
    feeding_rate: 3.5,
    rate_min: 3.0,
    rate_max: 4.0,
    priority: 25,
    source: 'ICAR-CIFA Grow-out Reference Protocol',
    notes: 'Mid stage: 3–4% body weight/day (Reference range, working value: 3.5%)',
    notes_mr: 'मध्यम टप्पा: ३–४% बायोमास/दिवस (संदर्भ श्रेणी, कार्य दर: ३.५%)',
  },
  {
    id: 'rohu-growout-final',
    species: 'Rohu',
    scientific_name: 'Labeo rohita',
    culture_stage: 'Grow-out',
    growout_phase: 'final',
    min_weight: null,
    max_weight: null,
    min_month: null,
    max_month: null,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'REFERENCE_ASSUMPTION',
    feeding_rate: 2.5,
    rate_min: 2.0,
    rate_max: 3.0,
    priority: 25,
    source: 'ICAR-CIFA Grow-out Reference Protocol',
    notes: 'Final stage: 2–3% body weight/day (Reference range, working value: 2.5%)',
    notes_mr: 'अंतिम टप्पा: २–३% बायोमास/दिवस (संदर्भ श्रेणी, कार्य दर: २.५%)',
  },

  // ===============================================================
  // IMC SPECIES: CATLA (Catla catla)
  // ===============================================================
  {
    id: 'catla-nursery',
    species: 'Catla',
    scientific_name: 'Catla catla',
    culture_stage: 'Nursery',
    min_weight: null,
    max_weight: null,
    min_month: null,
    max_month: null,
    feeding_method: 'INITIAL_SPAWN_WEIGHT',
    feeding_mode: 'MANUAL',
    feeding_rate: null, // Manual feeding selection required
    rate_min: 400.0,
    rate_max: 800.0,
    priority: 30,
    source: 'Project Reference Assumption & CIFA Nursery Protocol',
    notes: 'Biomass: 1M spawn = 1.5 kg (project assumption). Reference: 400% (first 5 days), 800% (after first 5 days). Manual rate required.',
    notes_mr: 'बायोमास विचार: १० लाख स्पॉन = १.५ किलो (प्रकल्प गृहीतक). संदर्भ: ४००% (पहिले ५ दिवस), ८००% (५ दिवसांनंतर). मॅन्युअल दर आवश्यक.',
  },
  {
    id: 'catla-rearing-m1',
    species: 'Catla',
    scientific_name: 'Catla catla',
    culture_stage: 'Rearing',
    rearing_period: 'month_1',
    min_weight: null,
    max_weight: null,
    min_month: 0.0,
    max_month: 1.0,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'REFERENCE_ASSUMPTION',
    feeding_rate: 9.0,
    rate_min: 8.0,
    rate_max: 10.0,
    priority: 25,
    source: 'ICAR-CIFA Rearing Reference Protocol',
    notes: 'First month: 8–10% body weight/day (Reference range, working value: 9%)',
    notes_mr: 'पहिला महिना: ८–१०% बायोमास/दिवस (संदर्भ श्रेणी, कार्य दर: ९%)',
  },
  {
    id: 'catla-rearing-m2',
    species: 'Catla',
    scientific_name: 'Catla catla',
    culture_stage: 'Rearing',
    rearing_period: 'month_2',
    min_weight: null,
    max_weight: null,
    min_month: 1.01,
    max_month: 2.0,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'REFERENCE_ASSUMPTION',
    feeding_rate: 7.0,
    rate_min: 6.0,
    rate_max: 8.0,
    priority: 25,
    source: 'ICAR-CIFA Rearing Reference Protocol',
    notes: 'Second month: 6–8% body weight/day (Reference range, working value: 7%)',
    notes_mr: 'दुसरा महिना: ६–८% बायोमास/दिवस (संदर्भ श्रेणी, कार्य दर: ७%)',
  },
  {
    id: 'catla-rearing-later',
    species: 'Catla',
    scientific_name: 'Catla catla',
    culture_stage: 'Rearing',
    rearing_period: 'later',
    min_weight: null,
    max_weight: null,
    min_month: 2.01,
    max_month: 99.0,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'REFERENCE_ASSUMPTION',
    feeding_rate: 5.5,
    rate_min: 5.0,
    rate_max: 6.0,
    priority: 25,
    source: 'ICAR-CIFA Rearing Reference Protocol',
    notes: 'Later stages: 5–6% body weight/day (Reference range, working value: 5.5%)',
    notes_mr: 'पुढील टप्पे: ५–६% बायोमास/दिवस (संदर्भ श्रेणी, कार्य दर: ५.५%)',
  },
  {
    id: 'catla-growout-initial',
    species: 'Catla',
    scientific_name: 'Catla catla',
    culture_stage: 'Grow-out',
    growout_phase: 'initial',
    min_weight: null,
    max_weight: null,
    min_month: null,
    max_month: null,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'REFERENCE_ASSUMPTION',
    feeding_rate: 5.5,
    rate_min: 5.0,
    rate_max: 6.0,
    priority: 25,
    source: 'ICAR-CIFA Grow-out Reference Protocol',
    notes: 'Initial stage: 5–6% body weight/day (Reference range, working value: 5.5%)',
    notes_mr: 'सुरुवातीचा टप्पा: ५–६% बायोमास/दिवस (संदर्भ श्रेणी, कार्य दर: ५.५%)',
  },
  {
    id: 'catla-growout-mid',
    species: 'Catla',
    scientific_name: 'Catla catla',
    culture_stage: 'Grow-out',
    growout_phase: 'mid',
    min_weight: null,
    max_weight: null,
    min_month: null,
    max_month: null,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'REFERENCE_ASSUMPTION',
    feeding_rate: 3.5,
    rate_min: 3.0,
    rate_max: 4.0,
    priority: 25,
    source: 'ICAR-CIFA Grow-out Reference Protocol',
    notes: 'Mid stage: 3–4% body weight/day (Reference range, working value: 3.5%)',
    notes_mr: 'मध्यम टप्पा: ३–४% बायोमास/दिवस (संदर्भ श्रेणी, कार्य दर: ३.५%)',
  },
  {
    id: 'catla-growout-final',
    species: 'Catla',
    scientific_name: 'Catla catla',
    culture_stage: 'Grow-out',
    growout_phase: 'final',
    min_weight: null,
    max_weight: null,
    min_month: null,
    max_month: null,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'REFERENCE_ASSUMPTION',
    feeding_rate: 2.5,
    rate_min: 2.0,
    rate_max: 3.0,
    priority: 25,
    source: 'ICAR-CIFA Grow-out Reference Protocol',
    notes: 'Final stage: 2–3% body weight/day (Reference range, working value: 2.5%)',
    notes_mr: 'अंतिम टप्पा: २–३% बायोमास/दिवस (संदर्भ श्रेणी, कार्य दर: २.५%)',
  },

  // ===============================================================
  // IMC SPECIES: MRIGAL (Cirrhinus cirrhosus)
  // ===============================================================
  {
    id: 'mrigal-nursery',
    species: 'Mrigal',
    scientific_name: 'Cirrhinus cirrhosus',
    culture_stage: 'Nursery',
    min_weight: null,
    max_weight: null,
    min_month: null,
    max_month: null,
    feeding_method: 'INITIAL_SPAWN_WEIGHT',
    feeding_mode: 'MANUAL',
    feeding_rate: null, // Manual feeding selection required
    rate_min: 400.0,
    rate_max: 800.0,
    priority: 30,
    source: 'Project Reference Assumption & CIFA Nursery Protocol',
    notes: 'Biomass: 1M spawn = 1.5 kg (project assumption). Reference: 400% (first 5 days), 800% (after first 5 days). Manual rate required.',
    notes_mr: 'बायोमास विचार: १० लाख स्पॉन = १.५ किलो (प्रकल्प गृहीतक). संदर्भ: ४००% (पहिले ५ दिवस), ८००% (५ दिवसांनंतर). मॅन्युअल दर आवश्यक.',
  },
  {
    id: 'mrigal-rearing-m1',
    species: 'Mrigal',
    scientific_name: 'Cirrhinus cirrhosus',
    culture_stage: 'Rearing',
    rearing_period: 'month_1',
    min_weight: null,
    max_weight: null,
    min_month: 0.0,
    max_month: 1.0,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'REFERENCE_ASSUMPTION',
    feeding_rate: 9.0,
    rate_min: 8.0,
    rate_max: 10.0,
    priority: 25,
    source: 'ICAR-CIFA Rearing Reference Protocol',
    notes: 'First month: 8–10% body weight/day (Reference range, working value: 9%)',
    notes_mr: 'पहिला महिना: ८–१०% बायोमास/दिवस (संदर्भ श्रेणी, कार्य दर: ९%)',
  },
  {
    id: 'mrigal-rearing-m2',
    species: 'Mrigal',
    scientific_name: 'Cirrhinus cirrhosus',
    culture_stage: 'Rearing',
    rearing_period: 'month_2',
    min_weight: null,
    max_weight: null,
    min_month: 1.01,
    max_month: 2.0,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'REFERENCE_ASSUMPTION',
    feeding_rate: 7.0,
    rate_min: 6.0,
    rate_max: 8.0,
    priority: 25,
    source: 'ICAR-CIFA Rearing Reference Protocol',
    notes: 'Second month: 6–8% body weight/day (Reference range, working value: 7%)',
    notes_mr: 'दुसरा महिना: ६–८% बायोमास/दिवस (संदर्भ श्रेणी, कार्य दर: ७%)',
  },
  {
    id: 'mrigal-rearing-later',
    species: 'Mrigal',
    scientific_name: 'Cirrhinus cirrhosus',
    culture_stage: 'Rearing',
    rearing_period: 'later',
    min_weight: null,
    max_weight: null,
    min_month: 2.01,
    max_month: 99.0,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'REFERENCE_ASSUMPTION',
    feeding_rate: 5.5,
    rate_min: 5.0,
    rate_max: 6.0,
    priority: 25,
    source: 'ICAR-CIFA Rearing Reference Protocol',
    notes: 'Later stages: 5–6% body weight/day (Reference range, working value: 5.5%)',
    notes_mr: 'पुढील टप्पे: ५–६% बायोमास/दिवस (संदर्भ श्रेणी, कार्य दर: ५.५%)',
  },
  {
    id: 'mrigal-growout-initial',
    species: 'Mrigal',
    scientific_name: 'Cirrhinus cirrhosus',
    culture_stage: 'Grow-out',
    growout_phase: 'initial',
    min_weight: null,
    max_weight: null,
    min_month: null,
    max_month: null,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'REFERENCE_ASSUMPTION',
    feeding_rate: 5.5,
    rate_min: 5.0,
    rate_max: 6.0,
    priority: 25,
    source: 'ICAR-CIFA Grow-out Reference Protocol',
    notes: 'Initial stage: 5–6% body weight/day (Reference range, working value: 5.5%)',
    notes_mr: 'सुरुवातीचा टप्पा: ५–६% बायोमास/दिवस (संदर्भ श्रेणी, कार्य दर: ५.५%)',
  },
  {
    id: 'mrigal-growout-mid',
    species: 'Mrigal',
    scientific_name: 'Cirrhinus cirrhosus',
    culture_stage: 'Grow-out',
    growout_phase: 'mid',
    min_weight: null,
    max_weight: null,
    min_month: null,
    max_month: null,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'REFERENCE_ASSUMPTION',
    feeding_rate: 3.5,
    rate_min: 3.0,
    rate_max: 4.0,
    priority: 25,
    source: 'ICAR-CIFA Grow-out Reference Protocol',
    notes: 'Mid stage: 3–4% body weight/day (Reference range, working value: 3.5%)',
    notes_mr: 'मध्यम टप्पा: ३–४% बायोमास/दिवस (संदर्भ श्रेणी, कार्य दर: ३.५%)',
  },
  {
    id: 'mrigal-growout-final',
    species: 'Mrigal',
    scientific_name: 'Cirrhinus cirrhosus',
    culture_stage: 'Grow-out',
    growout_phase: 'final',
    min_weight: null,
    max_weight: null,
    min_month: null,
    max_month: null,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'REFERENCE_ASSUMPTION',
    feeding_rate: 2.5,
    rate_min: 2.0,
    rate_max: 3.0,
    priority: 25,
    source: 'ICAR-CIFA Grow-out Reference Protocol',
    notes: 'Final stage: 2–3% body weight/day (Reference range, working value: 2.5%)',
    notes_mr: 'अंतिम टप्पा: २–३% बायोमास/दिवस (संदर्भ श्रेणी, कार्य दर: २.५%)',
  },

  // ===============================================================
  // COMMON CARP (Cyprinus carpio) - Weight-based Rules
  // Priority 50: Weight-specific rules take priority over generic stage rules
  // ===============================================================
  {
    id: 'cc-1-10',
    species: 'Common Carp',
    scientific_name: 'Cyprinus carpio',
    culture_stage: 'All',
    min_weight: 1.0,
    max_weight: 10.0,
    min_month: null,
    max_month: null,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'AUTOMATIC',
    feeding_rate: 20.0,
    rate_min: 20.0,
    rate_max: 20.0,
    priority: 50,
    source: 'FAO / ICAR Standard Carp Protocol',
    notes: '1–10 g: 20% body weight/day',
    notes_mr: '१–१० ग्रॅम: शरीराच्या वजनाच्या २०% दर',
  },
  {
    id: 'cc-10-90',
    species: 'Common Carp',
    scientific_name: 'Cyprinus carpio',
    culture_stage: 'All',
    min_weight: 10.01,
    max_weight: 90.0,
    min_month: null,
    max_month: null,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'AUTOMATIC',
    feeding_rate: 10.0,
    rate_min: 10.0,
    rate_max: 10.0,
    priority: 50,
    source: 'FAO / ICAR Standard Carp Protocol',
    notes: '10–90 g: 10% body weight/day',
    notes_mr: '१०–९० ग्रॅम: शरीराच्या वजनाच्या १०% दर',
  },
  {
    id: 'cc-100-200',
    species: 'Common Carp',
    scientific_name: 'Cyprinus carpio',
    culture_stage: 'All',
    min_weight: 90.01,
    max_weight: 200.0,
    min_month: null,
    max_month: null,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'AUTOMATIC',
    feeding_rate: 7.0,
    rate_min: 7.0,
    rate_max: 7.0,
    priority: 50,
    source: 'FAO / ICAR Standard Carp Protocol',
    notes: '100–200 g: 7% body weight/day',
    notes_mr: '१००–२०० ग्रॅम: शरीराच्या वजनाच्या ७% दर',
  },
  {
    id: 'cc-200-500',
    species: 'Common Carp',
    scientific_name: 'Cyprinus carpio',
    culture_stage: 'All',
    min_weight: 200.01,
    max_weight: 500.0,
    min_month: null,
    max_month: null,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'AUTOMATIC',
    feeding_rate: 4.8,
    rate_min: 4.8,
    rate_max: 4.8,
    priority: 50,
    source: 'FAO / ICAR Standard Carp Protocol',
    notes: '200–500 g: 4.8% body weight/day',
    notes_mr: '२००–५०० ग्रॅम: शरीराच्या वजनाच्या ४.८% दर',
  },
  {
    id: 'cc-500-900',
    species: 'Common Carp',
    scientific_name: 'Cyprinus carpio',
    culture_stage: 'All',
    min_weight: 500.01,
    max_weight: 900.0,
    min_month: null,
    max_month: null,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'AUTOMATIC',
    feeding_rate: 3.3,
    rate_min: 3.3,
    rate_max: 3.3,
    priority: 50,
    source: 'FAO / ICAR Standard Carp Protocol',
    notes: '500–900 g: 3.3% body weight/day',
    notes_mr: '५००–९०० ग्रॅम: शरीराच्या वजनाच्या ३.३% दर',
  },
  {
    id: 'cc-900-1000',
    species: 'Common Carp',
    scientific_name: 'Cyprinus carpio',
    culture_stage: 'All',
    min_weight: 900.01,
    max_weight: 1000.0,
    min_month: null,
    max_month: null,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'AUTOMATIC',
    feeding_rate: 2.4,
    rate_min: 2.4,
    rate_max: 2.4,
    priority: 50,
    source: 'FAO / ICAR Standard Carp Protocol',
    notes: '900–1000 g: 2.4% body weight/day',
    notes_mr: '९००–१००० ग्रॅम: शरीराच्या वजनाच्या २.४% दर',
  },
  {
    id: 'cc-1000-plus',
    species: 'Common Carp',
    scientific_name: 'Cyprinus carpio',
    culture_stage: 'All',
    min_weight: 1000.01,
    max_weight: 99999.0,
    min_month: null,
    max_month: null,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'AUTOMATIC',
    feeding_rate: 2.0,
    rate_min: 1.8,
    rate_max: 2.2,
    priority: 40,
    source: 'FAO / ICAR Standard Carp Protocol',
    notes: '>1000 g: 2% body weight/day',
    notes_mr: '>१००० ग्रॅम: शरीराच्या वजनाच्या २% दर',
  },

  // ===============================================================
  // TILAPIA (Oreochromis spp.) - Weight-based Rules with Range
  // ===============================================================
  {
    id: 'tilapia-under-10',
    species: 'Tilapia',
    scientific_name: 'Oreochromis spp.',
    culture_stage: 'All',
    min_weight: 0.01,
    max_weight: 9.99,
    min_month: null,
    max_month: null,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'REFERENCE_ASSUMPTION',
    feeding_rate: 8.0,
    rate_min: 7.0,
    rate_max: 9.0,
    priority: 50,
    source: 'FAO Tilapia Feed Management',
    notes: '<10 g: 7–9% body weight/day (Reference range, working value: 8%)',
    notes_mr: '<१० ग्रॅम: ७–९% बायोमास/दिवस (संदर्भ श्रेणी, कार्य दर: ८%)',
  },
  {
    id: 'tilapia-10-40',
    species: 'Tilapia',
    scientific_name: 'Oreochromis spp.',
    culture_stage: 'All',
    min_weight: 10.0,
    max_weight: 39.99,
    min_month: null,
    max_month: null,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'REFERENCE_ASSUMPTION',
    feeding_rate: 7.0,
    rate_min: 6.0,
    rate_max: 8.0,
    priority: 50,
    source: 'FAO Tilapia Feed Management',
    notes: '10–40 g: 6–8% body weight/day (Reference range, working value: 7%)',
    notes_mr: '१०–४० ग्रॅम: ६–८% बायोमास/दिवस (संदर्भ श्रेणी, कार्य दर: ७%)',
  },
  {
    id: 'tilapia-40-100',
    species: 'Tilapia',
    scientific_name: 'Oreochromis spp.',
    culture_stage: 'All',
    min_weight: 40.0,
    max_weight: 99.99,
    min_month: null,
    max_month: null,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'REFERENCE_ASSUMPTION',
    feeding_rate: 6.0,
    rate_min: 5.0,
    rate_max: 7.0,
    priority: 50,
    source: 'FAO Tilapia Feed Management',
    notes: '40–100 g: 5–7% body weight/day (Reference range, working value: 6%)',
    notes_mr: '४०–१०० ग्रॅम: ५–७% बायोमास/दिवस (संदर्भ श्रेणी, कार्य दर: ६%)',
  },
  {
    id: 'tilapia-over-100',
    species: 'Tilapia',
    scientific_name: 'Oreochromis spp.',
    culture_stage: 'All',
    min_weight: 100.0,
    max_weight: 99999.0,
    min_month: null,
    max_month: null,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'REFERENCE_ASSUMPTION',
    feeding_rate: 4.0,
    rate_min: 3.0,
    rate_max: 5.0,
    priority: 50,
    source: 'FAO Tilapia Feed Management',
    notes: '>100 g: 3–5% body weight/day (Reference range, working value: 4%)',
    notes_mr: '>१०० ग्रॅम: ३–५% बायोमास/दिवस (संदर्भ श्रेणी, कार्य दर: ४%)',
  },

  // ===============================================================
  // PANGASIUS (Pangasianodon hypophthalmus) - Culture Period Rules
  // ===============================================================
  {
    id: 'pangasius-m1-2',
    species: 'Pangasius',
    scientific_name: 'Pangasianodon hypophthalmus',
    culture_stage: 'All',
    min_weight: null,
    max_weight: null,
    min_month: 0.0,
    max_month: 2.0,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'AUTOMATIC',
    feeding_rate: 5.0,
    rate_min: 5.0,
    rate_max: 5.0,
    priority: 35,
    source: 'ICAR-CIFA Pangasius Protocol',
    notes: 'First 2 months: 5% body weight/day',
    notes_mr: 'पहिले २ महिने: बायोमासच्या ५% दर',
  },
  {
    id: 'pangasius-m3-5',
    species: 'Pangasius',
    scientific_name: 'Pangasianodon hypophthalmus',
    culture_stage: 'All',
    min_weight: null,
    max_weight: null,
    min_month: 2.01,
    max_month: 5.0,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'AUTOMATIC',
    feeding_rate: 3.0,
    rate_min: 3.0,
    rate_max: 3.0,
    priority: 35,
    source: 'ICAR-CIFA Pangasius Protocol',
    notes: '3rd–5th month: 3% body weight/day',
    notes_mr: 'महिने ३–५: बायोमासच्या ३% दर',
  },
  {
    id: 'pangasius-m6-plus',
    species: 'Pangasius',
    scientific_name: 'Pangasianodon hypophthalmus',
    culture_stage: 'All',
    min_weight: null,
    max_weight: null,
    min_month: 5.01,
    max_month: 99.0,
    feeding_method: 'BIOMASS_PERCENT',
    feeding_mode: 'AUTOMATIC',
    feeding_rate: 2.0,
    rate_min: 2.0,
    rate_max: 2.0,
    priority: 35,
    source: 'ICAR-CIFA Pangasius Protocol',
    notes: '6th month onward: 2% body weight/day',
    notes_mr: 'महिना ६ आणि पुढे: बायोमासच्या २% दर',
  },

  // ===============================================================
  // MAGUR (Clarias batrachus) - MANUAL FEEDING MODE
  // Fishry does NOT have a universal automatic feeding percentage for Magur
  // ===============================================================
  {
    id: 'magur-manual',
    species: 'Magur',
    scientific_name: 'Clarias batrachus',
    culture_stage: 'All',
    min_weight: null,
    max_weight: null,
    min_month: null,
    max_month: null,
    feeding_method: 'MANUAL',
    feeding_mode: 'MANUAL',
    feeding_rate: null, // No universal automatic rate
    rate_min: null,
    rate_max: null,
    priority: 30,
    source: 'Farmer Verified Culture/Feed Protocol',
    notes: 'No universal automatic feeding rate applied. Farmer must enter a verified feeding rate manually.',
    notes_mr: 'मागूरसाठी कोणताही सार्वत्रिक स्वयंचलित दर नाही. शेतकऱ्याने स्वतः प्रमाणित दर भरावा.',
  },

  // ===============================================================
  // GRASS CARP (Ctenopharyngodon idella) - SPECIAL FEEDING METHOD
  // Fishry does NOT apply a universal automatic pellet feeding rate
  // ===============================================================
  {
    id: 'grass-carp-manual',
    species: 'Grass Carp',
    scientific_name: 'Ctenopharyngodon idella',
    culture_stage: 'All',
    min_weight: null,
    max_weight: null,
    min_month: null,
    max_month: null,
    feeding_method: 'FORAGE_BASED',
    feeding_mode: 'MANUAL',
    feeding_rate: null, // No universal automatic pellet rate
    rate_min: null,
    rate_max: null,
    priority: 30,
    source: 'Forage-based / Supplementary Manual Protocol',
    notes: 'Feeding depends on forage/vegetation availability. Fishry does not apply a universal automatic pellet feeding rate.',
    notes_mr: 'खाद्य वनस्पती व चाऱ्यावर अवलंबून असते. Fishry स्वयंचलित गोळी खाद्य दर लागू करत नाही.',
  },
];
